### ISSUE TITLE
useStore vs useSelector

### ISSUE THREAD

**Issue by alizarion** [angelguzmaning/ts-redux-react-realworld-example-app#1]
First of all I want to say that it is an excellent job , thank you for this contribution, I find this approach very interesting and I try to integrate it into an NX project. 

while browsing the code I was wondering if there is a particular reason not to have used selector and the hook UseSelector instead of useStore as pattern.

**Comment by angelguzmaning** [comment]
Yes, I'm not a big fan of using providers in a Typescript application because you would need to infer the type when you access the provider's data. That's why I instead built an equivalent hook that is type-safe for this application.
