### ISSUE TITLE
Permission to use this project in a video

### ISSUE THREAD

**Issue by jamsea** [angelguzmaning/ts-redux-react-realworld-example-app#5]
Hey @angelguzmaning, I couldn't find your contact info so I figured I'd just open an issue.

I teach engineers how to do DevOps (setting up CI/CD pipelines, on-call rotations, monitoring, etc). I'm putting together a free video to show engineers the modern way of deploying and monitoring software. Instead of making my own example app I'd love to use this as a demo. I couldn't find the code license anywhere, are you ok with me doing this? 

If you're not, that's cool! I was just really impressed with all the modern best practices you've done here.

**Comment by angelguzmaning** [comment]
Hey @jamsea, you are totally welcome to use this project as a demo, good luck with your video! And if the video will public, let me know when you publish it : D
