### ISSUE TITLE
Validation on different form

### ISSUE THREAD

**Issue by DatTranPTN** [angelguzmaning/ts-redux-react-realworld-example-app#9]
Hi, I wonder if when I work on 2 different functions but use the same GenericForm.tsx and FormGroup.tsx, how could I set the validation for one function but not in the other. Or I just create another GenericForm and FormGroup for my own purpose.

**Comment by angelguzmaning** [comment]
Those components don't really deal with validations of their inputs (the GenericForm shows errors you send as a property). You could add some state to your function or to the slides and update it with the validation error messages, and then send those messages to the GenericForm as a property. And don't do it for the other function.

**Comment by DatTranPTN** [comment]
Hi, thank you for your feedback, also I would like to add some validation that related to coloring the text field when it has an error after submitting as this image, is that the same way as what you mentioned before?!
![image](https://user-images.githubusercontent.com/91057725/150045891-b16a090c-41ea-4e75-9b33-d9dcbde86565.png)

**Comment by angelguzmaning** [comment]
For that case, you will need to create your own component or modify the ones I created. Also maybe check the https://formik.org/, it probably already has utilities useful for your case
